name: Deploy Serverless to AWS
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  push:
    branches:
        - main
        - feature**
  workflow_dispatch:

jobs: 
  Deploy-Dev: # In reality we would likely use a re-usable github action to DRY this out. Kept for clarity.
    runs-on: ubuntu-latest 
    environment: dev
    name: dev
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: OutputRole
        run: |
          echo ${{vars.DEPLOYROLE}}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{vars.DEPLOYROLE}}
          role-session-name: serverless-python-demo
          aws-region: us-east-2
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Install Serverless/Plugins
        run: npm ci
      - name: Set Branch name to $STAGE env var
        run: |
          BRANCH="$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
          BRANCH="${BRANCH,,}"
          echo "BRANCH is $BRANCH"
          echo "STAGE=$BRANCH" >> "$GITHUB_ENV"
        # echo "::set-env name=STAGE::$BRANCH"
      - name: Serverless Deploy
        run: npx serverless deploy --stage dev-$STAGE --conceal